spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    url: jdbc:h2:mem:testdb
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    show-sql: 'true'
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
